train:
  data: "data/processed/churn_data_prepared.csv"
  model: "models"
  random_state: 42
  n_estimators: 100
  max_depth: 5
hyperparameter_grids:
  RandomForest:
    n_estimators: [100, 200]
    max_depth: [5, 10, None]
    min_samples_split: [2, 5]
    min_samples_leaf: [1, 2]
  LogisticRegression:
    C: [0.1, 1.0, 10.0]
    penalty: ['l1', 'l2']
    solver: ['liblinear']
  GradientBoosting:
    n_estimators: [100, 200]
    learning_rate: [0.01, 0.1]
    max_depth: [3, 5]
  XGBoost:
    n_estimators: [100, 200]
    max_depth: [3, 5]
    learning_rate: [0.01, 0.1]